### PR TITLE
refactor services from attributes to properties for lazy initializati…

### PR DESCRIPTION
**Pull request by lazyduo**
…on and docs

- [ ] pytest

TASK ID : CU-86ep1tdfb

### CODE REVIEW

**Comment by lazyduo** [comment]
Task linked: [CU-86ep1tdfb refactor services from attributes to properties](https://app.clickup.com/t/86ep1tdfb)

**Comment by nokchalatte** [comment]
pytest 확인 완료~ pre-commit 필요한가요?

image

**Comment by lazyduo** [comment]
@nokchalatte pre-commit 제가 방금 돌렸습니다.

**Review by nokchalatte — APPROVED** [review]
LGTM~

**Pull request merged**
